services:
  go-api:
    build:
      context: ./ # Adjust to the directory containing your Go API Dockerfile
    container_name: go-api
    ports:
      - "8000:8000" # Expose the Go API on port 8080
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
    env_file:
      - .env
    depends_on:
      - redis

  redis:
    image: redis:latest
    container_name: redis
    restart: always
    ports:
      - "6379:6379" # Expose Redis on port 6379
    volumes:
      - redis_data:/data
    command: ["redis-server"]

volumes:
  redis_data:
